"""NestorNotes CLI — typed shell interface to the NestorNotes MCP server.

The `cli` module is generated by `fastmcp generate-cli` from the server's tool
registry and committed. To regenerate after a tool change, run `make regenerate-cli`.
"""

__version__ = "0.1.0"
