#!/usr/bin/env python3
"""nestornotes — command-line client for the NestorNotes knowledge base.

Generated by `fastmcp generate-cli` (do not hand-edit). Regenerate with
`make regenerate-cli`. The CLIENT_SPEC defaults to the hosted production
endpoint; override with ``NESTORNOTES_SERVER_URL`` env var or pass
``--server URL`` flags via your shell wrapper.
"""
import json
import os
import sys
from typing import Annotated

import cyclopts
import mcp.types
from rich.console import Console

from fastmcp import Client


# CLIENT_SPEC is the MCP endpoint the CLI talks to. Override per-environment
# with the NESTORNOTES_SERVER_URL env var.
CLIENT_SPEC = os.environ.get("NESTORNOTES_SERVER_URL", "https://mcp.nestornotes.com/mcp")


def _build_auth():
    """Build the fastmcp Client `auth` argument from environment.

    NESTORNOTES_AUTH controls the strategy:
      - unset / "oauth"  → persistent browser-based OAuth (default)
      - "none"           → no auth (only useful against a local server with auth disabled)
      - "Bearer <token>" → explicit bearer token (CI / headless agents)

    OAuth tokens are cached on disk under NESTORNOTES_TOKEN_DIR
    (default: ~/.config/nestornotes/oauth/) so the browser flow only
    runs once per server URL.
    """
    import pathlib

    raw = os.environ.get("NESTORNOTES_AUTH", "oauth").strip()
    lower = raw.lower()

    if lower == "none":
        return None
    if lower != "oauth":
        # Anything else (e.g. "Bearer eyJhbGc...") is passed through to fastmcp.
        return raw

    from fastmcp.client.auth import OAuth
    from key_value.aio.stores.disk import DiskStore

    cache_dir = pathlib.Path(
        os.environ.get(
            "NESTORNOTES_TOKEN_DIR",
            str(pathlib.Path.home() / ".config" / "nestornotes" / "oauth"),
        )
    ).expanduser()
    cache_dir.mkdir(parents=True, exist_ok=True)

    return OAuth(token_storage=DiskStore(directory=str(cache_dir)))


CLIENT_AUTH = _build_auth()

app = cyclopts.App(name="nestornotes", help="NestorNotes CLI \u2014 typed shell access to your knowledge base.")
call_tool_app = cyclopts.App(name="call-tool", help="Call a tool on the server")
app.command(call_tool_app)

console = Console()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _print_tool_result(result):
    if result.is_error:
        for block in result.content:
            if isinstance(block, mcp.types.TextContent):
                console.print(f"[bold red]Error:[/bold red] {block.text}")
            else:
                console.print(f"[bold red]Error:[/bold red] {block}")
        sys.exit(1)

    if result.structured_content is not None:
        console.print_json(json.dumps(result.structured_content))
        return

    for block in result.content:
        if isinstance(block, mcp.types.TextContent):
            console.print(block.text)
        elif isinstance(block, mcp.types.ImageContent):
            size = len(block.data) * 3 // 4
            console.print(f"[dim][Image: {block.mimeType}, ~{size} bytes][/dim]")
        elif isinstance(block, mcp.types.AudioContent):
            size = len(block.data) * 3 // 4
            console.print(f"[dim][Audio: {block.mimeType}, ~{size} bytes][/dim]")


async def _call_tool(tool_name: str, arguments: dict) -> None:
    # Filter out None values and empty lists (defaults for optional array params)
    filtered = {
        k: v
        for k, v in arguments.items()
        if v is not None and (not isinstance(v, list) or len(v) > 0)
    }
    async with Client(CLIENT_SPEC, auth=CLIENT_AUTH) as client:
        result = await client.call_tool(tool_name, filtered, raise_on_error=False)
        _print_tool_result(result)
        if result.is_error:
            sys.exit(1)


# ---------------------------------------------------------------------------
# List / read commands
# ---------------------------------------------------------------------------


@app.command
async def list_tools() -> None:
    """List available tools."""
    async with Client(CLIENT_SPEC, auth=CLIENT_AUTH) as client:
        tools = await client.list_tools()
        if not tools:
            console.print("[dim]No tools found.[/dim]")
            return
        for tool in tools:
            sig_parts = []
            props = tool.inputSchema.get("properties", {})
            required = set(tool.inputSchema.get("required", []))
            for pname, pschema in props.items():
                ptype = pschema.get("type", "string")
                if pname in required:
                    sig_parts.append(f"{pname}: {ptype}")
                else:
                    sig_parts.append(f"{pname}: {ptype} = ...")
            sig = f"{tool.name}({', '.join(sig_parts)})"
            console.print(f"  [cyan]{sig}[/cyan]")
            if tool.description:
                console.print(f"    {tool.description}")
            console.print()


@app.command
async def list_resources() -> None:
    """List available resources."""
    async with Client(CLIENT_SPEC, auth=CLIENT_AUTH) as client:
        resources = await client.list_resources()
        if not resources:
            console.print("[dim]No resources found.[/dim]")
            return
        for r in resources:
            console.print(f"  [cyan]{r.uri}[/cyan]")
            desc_parts = [r.name or "", r.description or ""]
            desc = " — ".join(p for p in desc_parts if p)
            if desc:
                console.print(f"    {desc}")
        console.print()


@app.command
async def read_resource(uri: Annotated[str, cyclopts.Parameter(help="Resource URI")]) -> None:
    """Read a resource by URI."""
    async with Client(CLIENT_SPEC, auth=CLIENT_AUTH) as client:
        contents = await client.read_resource(uri)
        for block in contents:
            if isinstance(block, mcp.types.TextResourceContents):
                console.print(block.text)
            elif isinstance(block, mcp.types.BlobResourceContents):
                size = len(block.blob) * 3 // 4
                console.print(f"[dim][Blob: {block.mimeType}, ~{size} bytes][/dim]")


@app.command
async def list_prompts() -> None:
    """List available prompts."""
    async with Client(CLIENT_SPEC, auth=CLIENT_AUTH) as client:
        prompts = await client.list_prompts()
        if not prompts:
            console.print("[dim]No prompts found.[/dim]")
            return
        for p in prompts:
            args_str = ""
            if p.arguments:
                parts = [a.name for a in p.arguments]
                args_str = f"({', '.join(parts)})"
            console.print(f"  [cyan]{p.name}{args_str}[/cyan]")
            if p.description:
                console.print(f"    {p.description}")
        console.print()


@app.command
async def get_prompt(
    name: Annotated[str, cyclopts.Parameter(help="Prompt name")],
    *arguments: str,
) -> None:
    """Get a prompt by name. Pass arguments as key=value pairs."""
    parsed: dict[str, str] = {}
    for arg in arguments:
        if "=" not in arg:
            console.print(f"[bold red]Error:[/bold red] Invalid argument {arg!r} — expected key=value")
            sys.exit(1)
        key, value = arg.split("=", 1)
        parsed[key] = value

    async with Client(CLIENT_SPEC, auth=CLIENT_AUTH) as client:
        result = await client.get_prompt(name, parsed or None)
        for msg in result.messages:
            console.print(f"[bold]{msg.role}:[/bold]")
            if isinstance(msg.content, mcp.types.TextContent):
                console.print(f"  {msg.content.text}")
            elif isinstance(msg.content, mcp.types.ImageContent):
                size = len(msg.content.data) * 3 // 4
                console.print(f"  [dim][Image: {msg.content.mimeType}, ~{size} bytes][/dim]")
            else:
                console.print(f"  {msg.content}")
            console.print()


# ---------------------------------------------------------------------------
# Tool commands (generated from server schema)
# ---------------------------------------------------------------------------

@call_tool_app.command(name='toggle_bookmark')
async def toggle_bookmark(
    *,
    knowledge_id: Annotated[str, cyclopts.Parameter(help="The knowledge_metadata UUID.")],
    bookmarked: Annotated[bool, cyclopts.Parameter(help="True to bookmark, False to unbookmark.")],
) -> None:
    '''Set or unset the bookmark flag on a knowledge item.'''
    await _call_tool('toggle_bookmark', {'knowledge_id': knowledge_id, 'bookmarked': bookmarked})


@call_tool_app.command(name='toggle_archive')
async def toggle_archive(
    *,
    knowledge_id: Annotated[str, cyclopts.Parameter(help="The knowledge_metadata UUID.")],
    archived: Annotated[bool, cyclopts.Parameter(help="True to archive, False to unarchive.")],
) -> None:
    '''Archive or unarchive a knowledge item.

Archived items are excluded from digests and default views.'''
    await _call_tool('toggle_archive', {'knowledge_id': knowledge_id, 'archived': archived})


@call_tool_app.command(name='mark_seen')
async def mark_seen(
    *,
    knowledge_id: Annotated[str, cyclopts.Parameter(help="The knowledge_metadata UUID.")],
    seen: Annotated[bool, cyclopts.Parameter(help="True to mark seen (default), False to mark unseen.")] = True,
) -> None:
    '''Mark a knowledge item as seen or unseen.'''
    await _call_tool('mark_seen', {'knowledge_id': knowledge_id, 'seen': seen})


@call_tool_app.command(name='add_tag_to_item')
async def add_tag_to_item(
    *,
    knowledge_id: Annotated[str, cyclopts.Parameter(help="The knowledge_metadata UUID.")],
    tag_name: Annotated[str, cyclopts.Parameter(help="The tag name to add.")],
) -> None:
    '''Add a tag to a knowledge item. Creates the tag if it doesn\'t exist.'''
    await _call_tool('add_tag_to_item', {'knowledge_id': knowledge_id, 'tag_name': tag_name})


@call_tool_app.command(name='remove_tag_from_item')
async def remove_tag_from_item(
    *,
    knowledge_id: Annotated[str, cyclopts.Parameter(help="The knowledge_metadata UUID.")],
    tag_name: Annotated[str, cyclopts.Parameter(help="The tag name to remove.")],
) -> None:
    '''Remove a tag from a knowledge item.'''
    await _call_tool('remove_tag_from_item', {'knowledge_id': knowledge_id, 'tag_name': tag_name})


@call_tool_app.command(name='collection_search')
async def collection_search(
    *,
    query: Annotated[str, cyclopts.Parameter(help="Natural language question or topic to search for.")],
    collection_id: Annotated[str | None, cyclopts.Parameter(help="Optional collection UUID to scope the search.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Optional collection UUID to scope the search.\"\n                          }")] = None,
) -> None:
    '''Search user\'s knowledge base using AI-powered hybrid search.

This tool uses an AI agent that:
1. Classifies whether the query needs a search
2. Optimizes the query for better results
3. Runs both vector similarity AND keyword search
4. Merges and deduplicates results

More powerful than direct semantic_search/keyword_search for complex
or ambiguous queries. Use this for natural language questions.'''
    # Parse JSON parameters
    collection_id_parsed = json.loads(collection_id) if isinstance(collection_id, str) else collection_id

    await _call_tool('collection_search', {'query': query, 'collection_id': collection_id_parsed})


@call_tool_app.command(name='list_articles')
async def list_articles(
    *,
    collection_id: Annotated[str | None, cyclopts.Parameter(help="Optional collection UUID to scope results.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Optional collection UUID to scope results.\"\n                          }")] = None,
    created_after: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp — only return articles created after this time.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp — only return articles created after this time.\"\n                          }")] = None,
    created_before: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp — only return articles created before this time.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp — only return articles created before this time.\"\n                          }")] = None,
    limit: Annotated[int, cyclopts.Parameter(help="Max results to return (default 20, max 100).")] = 20,
    offset: Annotated[int, cyclopts.Parameter(help="Pagination offset.")] = 0,
) -> None:
    '''List saved articles with pagination and time filtering.

Returns article metadata (no full content). Use get_article for full content.'''
    # Parse JSON parameters
    collection_id_parsed = json.loads(collection_id) if isinstance(collection_id, str) else collection_id
    created_after_parsed = json.loads(created_after) if isinstance(created_after, str) else created_after
    created_before_parsed = json.loads(created_before) if isinstance(created_before, str) else created_before

    await _call_tool('list_articles', {'collection_id': collection_id_parsed, 'created_after': created_after_parsed, 'created_before': created_before_parsed, 'limit': limit, 'offset': offset})


@call_tool_app.command(name='get_article')
async def get_article(
    *,
    article_id: Annotated[str, cyclopts.Parameter(help="The article UUID.")],
) -> None:
    '''Get a saved article by its ID.

Returns the article metadata and content. Only returns articles
owned by the authenticated user (enforced by RLS).'''
    await _call_tool('get_article', {'article_id': article_id})


@call_tool_app.command(name='get_article_summary')
async def get_article_summary(
    *,
    article_id: Annotated[str, cyclopts.Parameter(help="The article UUID.")],
) -> None:
    '''Get the AI-generated summary for an article.

Returns short description, key takeaways, and time-based summaries.'''
    await _call_tool('get_article_summary', {'article_id': article_id})


@call_tool_app.command(name='get_article_with_summary')
async def get_article_with_summary(
    *,
    article_id: Annotated[str, cyclopts.Parameter(help="The article UUID.")],
) -> None:
    '''Get an article together with its latest summary in one call.'''
    await _call_tool('get_article_with_summary', {'article_id': article_id})


@call_tool_app.command(name='list_bookmarked_items')
async def list_bookmarked_items(
    *,
    collection_id: Annotated[str | None, cyclopts.Parameter(help="Optional collection UUID to scope results.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Optional collection UUID to scope results.\"\n                          }")] = None,
    object_type: Annotated[str | None, cyclopts.Parameter(help="Filter by content type — one of 'article', 'incoming_emails',\n         'rss_item', 'youtube_item'.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Filter by content type — one of 'article', 'incoming_emails',\\n         'rss_item', 'youtube_item'.\"\n                          }")] = None,
    created_after: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp — only return items created after this time.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp — only return items created after this time.\"\n                          }")] = None,
    created_before: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp — only return items created before this time.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp — only return items created before this time.\"\n                          }")] = None,
    limit: Annotated[int, cyclopts.Parameter(help="Max results to return (default 20, max 100).")] = 20,
    offset: Annotated[int, cyclopts.Parameter(help="Pagination offset.")] = 0,
) -> None:
    '''List all bookmarked knowledge items.

Convenience tool that returns knowledge_metadata where bookmarked=True.'''
    # Parse JSON parameters
    collection_id_parsed = json.loads(collection_id) if isinstance(collection_id, str) else collection_id
    object_type_parsed = json.loads(object_type) if isinstance(object_type, str) else object_type
    created_after_parsed = json.loads(created_after) if isinstance(created_after, str) else created_after
    created_before_parsed = json.loads(created_before) if isinstance(created_before, str) else created_before

    await _call_tool('list_bookmarked_items', {'collection_id': collection_id_parsed, 'object_type': object_type_parsed, 'created_after': created_after_parsed, 'created_before': created_before_parsed, 'limit': limit, 'offset': offset})


@call_tool_app.command(name='list_collections')
async def list_collections(
) -> None:
    '''List all collections (workspaces) for the authenticated user.

Returns each collection\'s id, name, slug, and digest schedule.
Use this first to discover what collections exist before querying items.'''
    await _call_tool('list_collections', {})


@call_tool_app.command(name='get_collection')
async def get_collection(
    *,
    collection_id: Annotated[str, cyclopts.Parameter(help="The collection UUID.")],
) -> None:
    '''Get full details for a single collection.'''
    await _call_tool('get_collection', {'collection_id': collection_id})


@call_tool_app.command(name='list_emails')
async def list_emails(
    *,
    collection_id: Annotated[str | None, cyclopts.Parameter(help="Optional collection UUID to scope results.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Optional collection UUID to scope results.\"\n                          }")] = None,
    created_after: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp — only return emails created after this time.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp — only return emails created after this time.\"\n                          }")] = None,
    created_before: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp — only return emails created before this time.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp — only return emails created before this time.\"\n                          }")] = None,
    limit: Annotated[int, cyclopts.Parameter(help="Max results to return (default 20, max 100).")] = 20,
    offset: Annotated[int, cyclopts.Parameter(help="Pagination offset.")] = 0,
) -> None:
    '''List incoming emails with pagination and time filtering.

Returns email metadata (sender, subject). Use get_email for full content.'''
    # Parse JSON parameters
    collection_id_parsed = json.loads(collection_id) if isinstance(collection_id, str) else collection_id
    created_after_parsed = json.loads(created_after) if isinstance(created_after, str) else created_after
    created_before_parsed = json.loads(created_before) if isinstance(created_before, str) else created_before

    await _call_tool('list_emails', {'collection_id': collection_id_parsed, 'created_after': created_after_parsed, 'created_before': created_before_parsed, 'limit': limit, 'offset': offset})


@call_tool_app.command(name='get_email')
async def get_email(
    *,
    email_id: Annotated[str, cyclopts.Parameter(help="The incoming email UUID.")],
    include_body: Annotated[bool, cyclopts.Parameter(help="If True, also return the plain-text body extracted from\n          the parsed message. Can be large for newsletters.")] = False,
) -> None:
    '''Get a saved email by its ID.

Returns metadata only by default. The plain-text body can be large and
is opt-in via `include_body=True`. The raw `full_message` JSON and
rendered `html_email` are never returned — use `get_email_summary` for
the AI summary instead.'''
    await _call_tool('get_email', {'email_id': email_id, 'include_body': include_body})


@call_tool_app.command(name='get_email_summary')
async def get_email_summary(
    *,
    email_id: Annotated[str, cyclopts.Parameter(help="The incoming email UUID.")],
) -> None:
    '''Get the AI-generated summary for an email.'''
    await _call_tool('get_email_summary', {'email_id': email_id})


@call_tool_app.command(name='list_knowledge_items')
async def list_knowledge_items(
    *,
    collection_id: Annotated[str | None, cyclopts.Parameter(help="Optional collection UUID to scope results.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Optional collection UUID to scope results.\"\n                          }")] = None,
    object_type: Annotated[str | None, cyclopts.Parameter(help="Filter by content type — one of 'article', 'incoming_emails',\n         'rss_item', 'youtube_item'.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Filter by content type — one of 'article', 'incoming_emails',\\n         'rss_item', 'youtube_item'.\"\n                          }")] = None,
    summarized: Annotated[str | None, cyclopts.Parameter(help="If set, filter by whether the item has been summarized.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"boolean\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"If set, filter by whether the item has been summarized.\"\n                          }")] = None,
    bookmarked: Annotated[str | None, cyclopts.Parameter(help="If set, filter by bookmark status.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"boolean\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"If set, filter by bookmark status.\"\n                          }")] = None,
    archived: Annotated[str | None, cyclopts.Parameter(help="If set, filter by archive status.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"boolean\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"If set, filter by archive status.\"\n                          }")] = None,
    seen: Annotated[str | None, cyclopts.Parameter(help="If set, filter by seen status.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"boolean\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"If set, filter by seen status.\"\n                          }")] = None,
    created_after: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp — only return items created after this time.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp — only return items created after this time.\"\n                          }")] = None,
    created_before: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp — only return items created before this time.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp — only return items created before this time.\"\n                          }")] = None,
    updated_after: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp — only return items updated after this time.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp — only return items updated after this time.\"\n                          }")] = None,
    updated_before: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp — only return items updated before this time.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp — only return items updated before this time.\"\n                          }")] = None,
    limit: Annotated[int, cyclopts.Parameter(help="Max results to return (default 20, max 100).")] = 20,
    offset: Annotated[int, cyclopts.Parameter(help="Pagination offset.")] = 0,
) -> None:
    '''List knowledge items (articles, emails, RSS items, YouTube videos).

All results are automatically scoped to the authenticated user via RLS.
Supports filtering by collection, content type, summarization status,
bookmark/archive/seen state, and time range. Results are ordered newest-first.'''
    # Parse JSON parameters
    collection_id_parsed = json.loads(collection_id) if isinstance(collection_id, str) else collection_id
    object_type_parsed = json.loads(object_type) if isinstance(object_type, str) else object_type
    summarized_parsed = json.loads(summarized) if isinstance(summarized, str) else summarized
    bookmarked_parsed = json.loads(bookmarked) if isinstance(bookmarked, str) else bookmarked
    archived_parsed = json.loads(archived) if isinstance(archived, str) else archived
    seen_parsed = json.loads(seen) if isinstance(seen, str) else seen
    created_after_parsed = json.loads(created_after) if isinstance(created_after, str) else created_after
    created_before_parsed = json.loads(created_before) if isinstance(created_before, str) else created_before
    updated_after_parsed = json.loads(updated_after) if isinstance(updated_after, str) else updated_after
    updated_before_parsed = json.loads(updated_before) if isinstance(updated_before, str) else updated_before

    await _call_tool('list_knowledge_items', {'collection_id': collection_id_parsed, 'object_type': object_type_parsed, 'summarized': summarized_parsed, 'bookmarked': bookmarked_parsed, 'archived': archived_parsed, 'seen': seen_parsed, 'created_after': created_after_parsed, 'created_before': created_before_parsed, 'updated_after': updated_after_parsed, 'updated_before': updated_before_parsed, 'limit': limit, 'offset': offset})


@call_tool_app.command(name='get_knowledge_item')
async def get_knowledge_item(
    *,
    knowledge_id: Annotated[str, cyclopts.Parameter(help="The knowledge_metadata UUID.")],
) -> None:
    '''Get a single knowledge metadata record by its ID.'''
    await _call_tool('get_knowledge_item', {'knowledge_id': knowledge_id})


@call_tool_app.command(name='count_knowledge_items')
async def count_knowledge_items(
    *,
    collection_id: Annotated[str | None, cyclopts.Parameter(help="Optional collection UUID to scope.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Optional collection UUID to scope.\"\n                          }")] = None,
    object_type: Annotated[str | None, cyclopts.Parameter(help="Filter by content type.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Filter by content type.\"\n                          }")] = None,
    summarized: Annotated[str | None, cyclopts.Parameter(help="If set, filter by summarization status.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"boolean\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"If set, filter by summarization status.\"\n                          }")] = None,
    bookmarked: Annotated[str | None, cyclopts.Parameter(help="If set, filter by bookmark status.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"boolean\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"If set, filter by bookmark status.\"\n                          }")] = None,
    archived: Annotated[str | None, cyclopts.Parameter(help="If set, filter by archive status.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"boolean\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"If set, filter by archive status.\"\n                          }")] = None,
    seen: Annotated[str | None, cyclopts.Parameter(help="If set, filter by seen status.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"boolean\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"If set, filter by seen status.\"\n                          }")] = None,
    created_after: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp lower bound.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp lower bound.\"\n                          }")] = None,
    created_before: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp upper bound.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp upper bound.\"\n                          }")] = None,
) -> None:
    '''Count knowledge items matching the given filters.

Useful for getting totals before paginating through results.'''
    # Parse JSON parameters
    collection_id_parsed = json.loads(collection_id) if isinstance(collection_id, str) else collection_id
    object_type_parsed = json.loads(object_type) if isinstance(object_type, str) else object_type
    summarized_parsed = json.loads(summarized) if isinstance(summarized, str) else summarized
    bookmarked_parsed = json.loads(bookmarked) if isinstance(bookmarked, str) else bookmarked
    archived_parsed = json.loads(archived) if isinstance(archived, str) else archived
    seen_parsed = json.loads(seen) if isinstance(seen, str) else seen
    created_after_parsed = json.loads(created_after) if isinstance(created_after, str) else created_after
    created_before_parsed = json.loads(created_before) if isinstance(created_before, str) else created_before

    await _call_tool('count_knowledge_items', {'collection_id': collection_id_parsed, 'object_type': object_type_parsed, 'summarized': summarized_parsed, 'bookmarked': bookmarked_parsed, 'archived': archived_parsed, 'seen': seen_parsed, 'created_after': created_after_parsed, 'created_before': created_before_parsed})


@call_tool_app.command(name='list_rss_subscriptions')
async def list_rss_subscriptions(
    *,
    collection_id: Annotated[str | None, cyclopts.Parameter(help="Optional collection UUID to scope results.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Optional collection UUID to scope results.\"\n                          }")] = None,
    created_after: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp — only return subscriptions created after this time.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp — only return subscriptions created after this time.\"\n                          }")] = None,
    created_before: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp — only return subscriptions created before this time.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp — only return subscriptions created before this time.\"\n                          }")] = None,
) -> None:
    '''List RSS channel subscriptions for the authenticated user.

Returns the subscription with embedded channel details (title, url).
Results are scoped to the authenticated user via RLS.'''
    # Parse JSON parameters
    collection_id_parsed = json.loads(collection_id) if isinstance(collection_id, str) else collection_id
    created_after_parsed = json.loads(created_after) if isinstance(created_after, str) else created_after
    created_before_parsed = json.loads(created_before) if isinstance(created_before, str) else created_before

    await _call_tool('list_rss_subscriptions', {'collection_id': collection_id_parsed, 'created_after': created_after_parsed, 'created_before': created_before_parsed})


@call_tool_app.command(name='list_rss_items')
async def list_rss_items(
    *,
    channel_id: Annotated[str, cyclopts.Parameter(help="The RSS channel UUID.")],
    published_after: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp — only items published after this.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp — only items published after this.\"\n                          }")] = None,
    published_before: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp — only items published before this.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp — only items published before this.\"\n                          }")] = None,
    limit: Annotated[int, cyclopts.Parameter(help="Max results (default 20, max 100).")] = 20,
) -> None:
    '''List recent items from an RSS channel.

Items are ordered by publication date (newest first). The `rss_item` table
has no `created_at`; use `published_after`/`published_before` to filter by
feed publication date instead.'''
    # Parse JSON parameters
    published_after_parsed = json.loads(published_after) if isinstance(published_after, str) else published_after
    published_before_parsed = json.loads(published_before) if isinstance(published_before, str) else published_before

    await _call_tool('list_rss_items', {'channel_id': channel_id, 'published_after': published_after_parsed, 'published_before': published_before_parsed, 'limit': limit})


@call_tool_app.command(name='get_rss_item_summary')
async def get_rss_item_summary(
    *,
    rss_item_id: Annotated[str, cyclopts.Parameter(help="The RSS item UUID.")],
) -> None:
    '''Get the AI-generated summary for an RSS item.'''
    await _call_tool('get_rss_item_summary', {'rss_item_id': rss_item_id})


@call_tool_app.command(name='semantic_search')
async def semantic_search(
    *,
    query: Annotated[str, cyclopts.Parameter(help="Natural language search query.")],
    collection_id: Annotated[str | None, cyclopts.Parameter(help="Optional collection UUID to scope search.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Optional collection UUID to scope search.\"\n                          }")] = None,
    limit: Annotated[int, cyclopts.Parameter(help="Max results (default 10, max 50).")] = 10,
) -> None:
    '''Search user\'s knowledge base using semantic similarity.

Uses vector embeddings to find content semantically related to the query.
Returns content snippets with metadata (title, URL, content type).'''
    # Parse JSON parameters
    collection_id_parsed = json.loads(collection_id) if isinstance(collection_id, str) else collection_id

    await _call_tool('semantic_search', {'query': query, 'collection_id': collection_id_parsed, 'limit': limit})


@call_tool_app.command(name='keyword_search')
async def keyword_search(
    *,
    query: Annotated[str, cyclopts.Parameter(help="Keywords to search for.")],
    collection_id: Annotated[str | None, cyclopts.Parameter(help="Optional collection UUID to scope search.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Optional collection UUID to scope search.\"\n                          }")] = None,
    limit: Annotated[int, cyclopts.Parameter(help="Max results (default 10, max 50).")] = 10,
    language: Annotated[str, cyclopts.Parameter(help="Text search language (default 'english').")] = 'english',
) -> None:
    '''Search user\'s knowledge base using full-text keyword matching.

Uses PostgreSQL full-text search for exact keyword matches with ranking.'''
    # Parse JSON parameters
    collection_id_parsed = json.loads(collection_id) if isinstance(collection_id, str) else collection_id

    await _call_tool('keyword_search', {'query': query, 'collection_id': collection_id_parsed, 'limit': limit, 'language': language})


@call_tool_app.command(name='list_tags')
async def list_tags(
) -> None:
    '''List all tags created by the authenticated user.'''
    await _call_tool('list_tags', {})


@call_tool_app.command(name='get_items_by_tag')
async def get_items_by_tag(
    *,
    tag_name: Annotated[str, cyclopts.Parameter(help="The tag name to filter by.")],
    collection_id: Annotated[str | None, cyclopts.Parameter(help="Optional collection UUID to scope results.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Optional collection UUID to scope results.\"\n                          }")] = None,
    object_type: Annotated[str | None, cyclopts.Parameter(help="Filter by content type — one of 'article', 'incoming_emails',\n         'rss_item', 'youtube_item'.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Filter by content type — one of 'article', 'incoming_emails',\\n         'rss_item', 'youtube_item'.\"\n                          }")] = None,
    created_after: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp lower bound.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp lower bound.\"\n                          }")] = None,
    created_before: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp upper bound.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp upper bound.\"\n                          }")] = None,
    limit: Annotated[int, cyclopts.Parameter(help="Max results (default 20, max 100).")] = 20,
    offset: Annotated[int, cyclopts.Parameter(help="Pagination offset.")] = 0,
) -> None:
    '''List knowledge items that have a specific tag.'''
    # Parse JSON parameters
    collection_id_parsed = json.loads(collection_id) if isinstance(collection_id, str) else collection_id
    object_type_parsed = json.loads(object_type) if isinstance(object_type, str) else object_type
    created_after_parsed = json.loads(created_after) if isinstance(created_after, str) else created_after
    created_before_parsed = json.loads(created_before) if isinstance(created_before, str) else created_before

    await _call_tool('get_items_by_tag', {'tag_name': tag_name, 'collection_id': collection_id_parsed, 'object_type': object_type_parsed, 'created_after': created_after_parsed, 'created_before': created_before_parsed, 'limit': limit, 'offset': offset})


@call_tool_app.command(name='get_tags_for_item')
async def get_tags_for_item(
    *,
    knowledge_id: Annotated[str, cyclopts.Parameter(help="The knowledge_metadata UUID.")],
) -> None:
    '''Get all tags associated with a specific knowledge item.'''
    await _call_tool('get_tags_for_item', {'knowledge_id': knowledge_id})


@call_tool_app.command(name='list_youtube_subscriptions')
async def list_youtube_subscriptions(
    *,
    collection_id: Annotated[str | None, cyclopts.Parameter(help="Optional collection UUID to scope results.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Optional collection UUID to scope results.\"\n                          }")] = None,
    created_after: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp — only return subscriptions created after this time.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp — only return subscriptions created after this time.\"\n                          }")] = None,
    created_before: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp — only return subscriptions created before this time.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp — only return subscriptions created before this time.\"\n                          }")] = None,
) -> None:
    '''List YouTube channel subscriptions for the authenticated user.

Returns subscriptions with embedded channel details.
Results are scoped to the authenticated user via RLS.'''
    # Parse JSON parameters
    collection_id_parsed = json.loads(collection_id) if isinstance(collection_id, str) else collection_id
    created_after_parsed = json.loads(created_after) if isinstance(created_after, str) else created_after
    created_before_parsed = json.loads(created_before) if isinstance(created_before, str) else created_before

    await _call_tool('list_youtube_subscriptions', {'collection_id': collection_id_parsed, 'created_after': created_after_parsed, 'created_before': created_before_parsed})


@call_tool_app.command(name='list_youtube_items')
async def list_youtube_items(
    *,
    channel_id: Annotated[str, cyclopts.Parameter(help="The YouTube channel UUID (internal, not the YT channel ID).")],
    published_after: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp lower bound on publication date.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp lower bound on publication date.\"\n                          }")] = None,
    published_before: Annotated[str | None, cyclopts.Parameter(help="ISO 8601 timestamp upper bound on publication date.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"ISO 8601 timestamp upper bound on publication date.\"\n                          }")] = None,
    limit: Annotated[int, cyclopts.Parameter(help="Max results (default 20, max 100).")] = 20,
) -> None:
    '''List recent videos from a YouTube channel.

Videos are ordered by `published_at` (newest first). The `youtube_item`
table has no `created_at` column.'''
    # Parse JSON parameters
    published_after_parsed = json.loads(published_after) if isinstance(published_after, str) else published_after
    published_before_parsed = json.loads(published_before) if isinstance(published_before, str) else published_before

    await _call_tool('list_youtube_items', {'channel_id': channel_id, 'published_after': published_after_parsed, 'published_before': published_before_parsed, 'limit': limit})


@call_tool_app.command(name='get_youtube_item')
async def get_youtube_item(
    *,
    youtube_item_id: Annotated[str, cyclopts.Parameter(help="The YouTube item UUID.")],
) -> None:
    '''Get a YouTube video including its transcript.'''
    await _call_tool('get_youtube_item', {'youtube_item_id': youtube_item_id})


@call_tool_app.command(name='get_youtube_item_summary')
async def get_youtube_item_summary(
    *,
    youtube_item_id: Annotated[str, cyclopts.Parameter(help="The YouTube item UUID.")],
) -> None:
    '''Get the AI-generated summary for a YouTube video.'''
    await _call_tool('get_youtube_item_summary', {'youtube_item_id': youtube_item_id})


def main() -> None:
    """Console-script entry point (declared in pyproject.toml)."""
    app()


if __name__ == "__main__":
    main()
